sudo: required
dist: trusty
language: cpp

services:
    - docker

compiler:
    - gcc

if: branch IN (master, testing)

env:
    - DOCKER_TARGET=xenial DOCKER_CXX=g++
    - DOCKER_TARGET=xenial DOCKER_CXX=clang++-4.0
    - DOCKER_TARGET=bionic DOCKER_CXX=g++

before_install:
    - docker build -t eos:${DOCKER_TARGET} -f .travis/${DOCKER_TARGET} .

script:
    - docker run -it -e COVERALLS_TOKEN eos:${DOCKER_TARGET} /bin/bash /src/.travis/build-and-test.bash ${DOCKER_TARGET} ${DOCKER_CXX}
